### ISSUE TITLE
Error on process exit

### ISSUE THREAD

**Issue by alanshaw** [ssbc/broadcast-stream#5]
```
dgram.js:630
    throw errnoException(err, 'dropMembership');
    ^

Error: dropMembership EINVAL
    at _errnoException (util.js:1021:11)
    at Socket.dropMembership (dgram.js:630:11)
    at process.<anonymous> (/Users/alan/Code/tableflip/vers/node_modules/broadcast-stream/index.js:12:12)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process.exit (internal/process.js:154:15)
    at process.on (/Users/alan/Code/tableflip/vers/index.js:28:15)
    at emitNone (events.js:105:13)
    at process.emit (events.js:207:7)
    at Signal.wrap.onsignal (internal/process.js:205:44)
```

**Comment by dominictarr** [comment]
hmm, maybe this is not needed anymore since reuseAddr is set? what do you think @clehner ?

**Comment by clehner** [comment]
Docs say:

> This method is automatically called by the kernel when the socket is closed or the process terminates, so most apps will never have reason to call this.

So i don't think it is needed

**Comment by mlegore** [comment]
I can also repro this issue when killing a child process used by ssb-party

**Comment by dominictarr** [comment]
does actually cause problems or does it just output an error message?

**Comment by mlegore** [comment]
It opens an error dialog on process exit for me, which looks bad to the user.

**Comment by dominictarr** [comment]
I disabled dropMembership in 0.2.2, let me know it works

**Comment by staltz** [comment]
Seems to be unnecessary, indeed.
